### ISSUE TITLE
Error in uncross.py

### ISSUE THREAD

**Issue by tkaria** [capitalk/strategy#2]
Traceback (most recent call last):
  File "uncross.py", line 286, in <module>
    strategy.run(md_update_wrapper, place_orders)
  File "/home/timir/capitalk/strategy/python/strategy_loop.py", line 228, in run
    self.order_manager.received_message_from_order_engine(tag, msg)
  File "/home/timir/capitalk/strategy/python/order_manager.py", line 310, in received_message_from_order_engine
    self._handle_execution_report(er)
  File "/home/timir/capitalk/strategy/python/order_manager.py", line 259, in _handle_execution_report
    (uuid_str(order_id), price, qty, filled_qty)
AssertionError: Unknown order id = c3abb6ac-6af4-4abc-9b81-66fd2dc104d4, price = 1.277700, qty = 1000000.0, filled = 1000000.0

**Comment by iskandr** [comment]
Turned out to be an annoying tiny bug, ahh well, fixed now.
